### ISSUE TITLE
Windows Implementation

### ISSUE THREAD

**Issue by ghost** [Fmstrat/youtube-dl-api#3]

**Comment by Fmstrat** [comment]
That's the URL you can reach the service at. So, let's say you're not using SSL and just doing this on a local network. Compose would look like this:

```
  youtube-dl-api:
    image: nowsci/youtube-dl-api
    container_name: youtube-dl-api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/video/Watch Later:/data
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - TOKEN=<yourtoken>
      - EXTHOST=http://192.168.0.111:8080
      - FORMAT=%(title)s - %(uploader)s - %(id)s.%(ext)s
    restart: always
```

Then, you would visit `http://192.168.0.111:8080?token=<mytoken>`. In this case, your windows machine has the IP 192.168.0.111.

The `ports` section says forward port 8080 from the host to 8080 on the container. The `environment` section sets environment variables inside the container (think things like PATH). Those variables are then used by the python script inside it.

That help?
